### PR TITLE
Bugfix/#137 fix basic auth

### LINKED ISSUE #137: httpBasicAuth does not work
I booted the server with the development profile and tried to access the api.
image

### PR DESCRIPTION
**Pull request by M4R1KU**
This closes #137 .

Summary of changes:
- ​basic auth is fixed finally

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [x] Update CI scripts on Semaphore (changes to `auth0.yml` or `application.yml`)

Please review @jmesserli @needToRoll / cc: @outcobra/developers.

### CODE REVIEW

**Comment by M4R1KU** [comment]
lul fück

**Comment by jmesserli** [comment]
Did you just merge error handling

**Comment by M4R1KU** [comment]
No I did not.

Joel Messerli <notifications@github.com> schrieb am Mi., 26. Apr. 2017,
19:47:

**Comment by jmesserli** [comment]
actually yes

**Comment by jmesserli** [comment]
grafik

**Comment by M4R1KU** [comment]
no i did not merge this pull request

Joel Messerli <notifications@github.com> schrieb am Mi., 26. Apr. 2017,
19:50:

**Comment by M4R1KU** [comment]
Look into the last commits on develop

**Pull request closed without merging**
