### PR TITLE
Bugfix/#213 sentry nullpointer

### LINKED ISSUE #213: Sentry: KotlinNullPointerException
https://sentry.pegnu.cloud/pg/outstanding-cobra/issues/59/

```
KotlinNullPointerException: None
    at outcobra.server.service.internal.DefaultSchoolClassService.readAllByUser(DefaultSchoolClassService.kt:31)
    at outcobra.server.service.internal.DefaultSchoolClassService$$FastClassBySpringCGLIB$$60eeae8e.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
...
(121 additional frame(s) were not displayed)

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is kotlin.KotlinNullPointerException] with root cause
```

### PR DESCRIPTION
**Pull request by needToRoll**
This closes #213
Summary of changes:
- removed `!!`operators
- fixed NullPointerExceptions
- updated ValidationExceptionThrower

I made sure to:
- [ ] ~~Add and / or update tests~~ _nothing to do_
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [ ] ~~Update CI script and configs on Jenkins (`Jenkinsfile`, `auth0.yml`, `application.yml`, etc.)~~ _nothing to do_

Please review @jmesserli  / cc: @outcobra/developers.

### CODE REVIEW

**Comment by needToRoll** [comment]
Can someone please tell me how to fix the jenkins build?  the pipline is green

**Comment by needToRoll** [comment]
@jmesserli why does the jenkins build fail? All steps are green imo

**Comment by jmesserli** [comment]
@needToRoll I would advise you to read the console output: https://ci.pegnu.cloud/job/outcobra/job/outstanding-cobra/job/bugfix%252F%2523213-sentry-nullpointer/1/console
That said, it's a bug in Jenkins with Docker. Should be fixed at some point in the future.

**Comment by needToRoll** [comment]
Ok I am sorry... can you merge it?

**Comment by jmesserli** [comment]
I still have some review comments that I've not gotten around to posting. Will update when I can.

**Pull request merged**
