### PR TITLE
implemented highlighting of insufficient marks

### LINKED ISSUE #327: Mark insufficient grades in a special way
It would be nice if insufficient grades would be marked as such to see faster which grades are "good" and which aren't.

### PR DESCRIPTION
**Pull request by needToRoll**
This closes #327.

Summary of changes:
- ​Insufficient marks are now displayed in darkred

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [x] Update CI script and configs on Jenkins (`Jenkinsfile`, `auth0.yml`, `application.yml`, etc.)

Please review @M4R1KU  / cc: @outcobra/developers.

### CODE REVIEW

**Comment by M4R1KU** [comment]
I have a suggestion: Use a directive.

**Comment by M4R1KU** [comment]
And darkred is to dark imo.

**Comment by needToRoll** [comment]
I agree, can you please provide a hex-color? I'm not much of a designer... as you know

**Comment by M4R1KU** [comment]
From now on I'd also like to have all color and font stuff (everything which is unfluenced by a theme) in a seperate theming file like `_auth-theming.scss`. Then you can use the warn color from the theme with `map-get(map-get($theme, warn), default)`. If you can't follow ask me on slack :D.

**Pull request merged**
