### PR TITLE
Feature/#220 edit manage entities

### LINKED ISSUE #220: Edit manage-entities
We should add the update functionality to the manage ui soon.
In my opinion this is a frontend debt and could be done inside this sprint.

### PR DESCRIPTION
**Pull request by M4R1KU**
This closes #220 

Summary of changes:
- ​manage entites can now be edited

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [x] Update CI script and configs on Jenkins (`Jenkinsfile`, `auth0.yml`, `application.yml`, etc.)

Please review @jmesserli  / cc: @outcobra/developers.

### CODE REVIEW

**Comment by jmesserli** [comment]
Please resolve merge conflicts to allow the jenkins build to run @needToRoll

**Comment by needToRoll** [comment]
It appears like there is a bug inside the update validation (I am going to fix this now).
I've found out that there is a problem with the "Petrol"-Color as well.

**Comment by needToRoll** [comment]
@M4R1KU what are those other changes you requested?

**Comment by needToRoll** [comment]
I was able to fix both bugs. 
Tested manually, ready to merge.
But accordig to the lable there are still some changes needed.

**Comment by M4R1KU** [comment]
@needToRoll The problem which exists is that the teacherId is null when we edit the subject. This is not a frontend issue. It's a backend validation issue.

**Pull request merged**
