### PR TITLE
Feature/#180 task desc optional

### LINKED ISSUE #180: Make description optional on task ui
I discussed with @M4R1KU that the task description should be optional to which he agreed.

So I as a user do not want to have to enter a description for my tasks so that I can save time and because the title often provides enough context on its own.

### PR DESCRIPTION
**Pull request by M4R1KU**
This closes #180 #182 #178 .

Summary of changes:
- ​made task description optional
- added error message when the dueDate is before the todoDate
- fixed ui bugs

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [x] Update CI scripts on Semaphore (changes to `auth0.yml` or `application.yml`)

Please review @jmesserli @needToRoll  / cc: @outcobra/developers.

### CODE REVIEW

**Comment by jmesserli** [comment]
Looks good, can you deploy to firebase?

**Comment by M4R1KU** [comment]
Later...

Joel Messerli <notifications@github.com> schrieb am Di., 28. März 2017,
08:34:

**Comment by M4R1KU** [comment]
It's deployed

**Comment by jmesserli** [comment]
Description is still not optional on firebase

**Comment by M4R1KU** [comment]
The newest version is now on firebase (with the firebase environment).

**Comment by needToRoll** [comment]
tested manually after short review, it appears to be fine

**Comment by jmesserli** [comment]
Thanks, you can merge then.

needToRoll <notifications@github.com> schrieb am Mo., 3. Apr. 2017, 19:42:

**Pull request merged**
