### PR TITLE
Bugfix/#310 exam task deletion

### LINKED ISSUE #267: Incomplete ExamDto after creation because of resused transaction
@needToRoll wrote a comment about a backend bug in the exam.component on line 143 and line 170.

Quick Links:
https://github.com/outcobra/outstanding-cobra/blob/19318030331d308e8188fb658093bb890541c87a/frontend/src/app/exam/exam.component.ts#L143
and
https://github.com/outcobra/outstanding-cobra/blob/19318030331d308e8188fb658093bb890541c87a/frontend/src/app/exam/exam.component.ts#L171

What is this bug?

### LINKED ISSUE #310: Can't remove learning objectives on exam
I want to be able to delete a learning objective at creation time and also later on

### PR DESCRIPTION
**Pull request by needToRoll**
This closes #310 closes #267

Summary of changes:
- ​Fix 130, allows the user to delete exam tasks. Deleting tasks only takes effect when submitting the dialog's form

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [ ] ~Update any documentation (javadoc, domain model, erd, ...)~
- [x] Follow the contribution guidelines
- [ ] ~Update CI script and configs on Jenkins (`Jenkinsfile`, `auth0.yml`, `application.yml`, etc.)~

Please review @**todo** / cc: @outcobra/developers.

### CODE REVIEW

**Comment by jmesserli** [comment]
Please resolve the merge conflicts

**Comment by M4R1KU** [comment]
This branch was created on an outdated version of develop.
The prefix of all material components is not "md" anymore, instead it is "mat"

**Comment by M4R1KU** [comment]
Can't we handle the deletion in the backend?

**Comment by M4R1KU** [comment]
Yes we can @M4R1KU

**Comment by jmesserli** [comment]
So does this resolve issue #267 now?

**Comment by M4R1KU** [comment]
Yeah most likely it does.

**Comment by M4R1KU** [comment]
Nope its not yet fixed

**Pull request merged**
