### PR TITLE
Upgrade/kotlin1.1.1

### PR DESCRIPTION
**Pull request by needToRoll**
This closes none.

Summary of changes:
- ​upgraded kotlin to 1.1.1
- added kotlin-spring
- added kotlin-allopen

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines

Please review @jmesserli  / cc: @outcobra/developers.

### CODE REVIEW

**Comment by needToRoll** [comment]
@jmesserli the readme is fine btw

**Comment by needToRoll** [comment]
dataloaders are broken... do not merge

**Comment by jmesserli** [comment]
@needToRoll actually it's not, the annotation processing should be enabled for backend-model too not just backend

**Comment by jmesserli** [comment]
Schribs neu

**Pull request merged**
