### PR TITLE
Amend/remove materialize css

### LINKED ISSUE #190: Remove Materializecss
We ought remove materializecss because we do not all it's potential and components.
Currently we mainly use the grid system and the typography part.

Tasks to be done:
- [ ] Remove the grid with and alternative (either [angular/flex-layout](https://github.com/angular/flex-layout) or flexgridcss)
- [ ] Remove the typography part and check why it does not work correctly with angular/material which should actually manage typography but does not
- [ ] search for other usages in the project and remove resp. replace them.

### LINKED ISSUE #211: Attribution is on top of navigation
The new attribution prevents the nagivation from being expanded on the lower half of the button, also see the image:
image

### PR DESCRIPTION
**Pull request by M4R1KU**
This closes #190 closes #211

This needs manual testing.

Summary of changes:
- added Montserrat as main Font-Family
- ​removed materialize css
- added angular/flex-layout
- use flex-layout instead of materialize grid

I made sure to:
- [x] Add and / or update tests
- [x] Run the code formatter (`CTRL + ALT + L`)
- [x] Update any documentation (javadoc, domain model, erd, ...)
- [x] Follow the contribution guidelines
- [x] Update CI script and configs on Jenkins (`Jenkinsfile`, `auth0.yml`, `application.yml`, etc.)

Please review @**todo** / cc: @outcobra/developers.

### CODE REVIEW

**Comment by jmesserli** [comment]
Please deploy this to Firebase

**Comment by M4R1KU** [comment]
Done

**Comment by jmesserli** [comment]
You forgot the firebase environment, Auth0 redirects to pegnu.cloud
`ng build -prod -e fire` (i think)

**Comment by M4R1KU** [comment]
Yeah now it should work

**Comment by M4R1KU** [comment]
Wut....

**Comment by jmesserli** [comment]
Thanks, works. What wut?

**Comment by M4R1KU** [comment]
It does not really work wtf....

**Comment by M4R1KU** [comment]
Now it works!!

**Comment by jmesserli** [comment]
Language switcher seems to no longer have a padding in the navigation on mobile

**Comment by M4R1KU** [comment]
Fixed language switcher too

**Pull request closed without merging**
